spring.application.name=factoryx-backend

server.port=${PORT:8081}


# =====================================================
# MYSQL
# =====================================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# SECURITY
# =====================================================

spring.security.user.name=admin
spring.security.user.password=admin123


# =====================================================
# SPRING AI + GROQ
# =====================================================

spring.ai.model.chat=openai

spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.ai.openai.chat.model=openai/gpt-oss-20b


# =====================================================
# DOCUMENT UPLOAD
# =====================================================

file.upload-dir=uploads/documents

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# =====================================================
# OLLAMA EMBEDDINGS
# =====================================================

spring.ai.model.embedding=ollama

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.embedding.model=mxbai-embed-large