spring.application.name=factoryx-backend

# =====================================================
# SERVER
# =====================================================

server.port=${PORT:8081}


# =====================================================
# MYSQL / TIDB CLOUD
# =====================================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# SPRING SECURITY
# =====================================================

spring.security.user.name=admin
spring.security.user.password=admin123


# =====================================================
# SPRING AI + GROQ
# =====================================================

spring.ai.model.chat=openai

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-20b


# =====================================================
# DOCUMENT UPLOAD
# =====================================================

file.upload-dir=uploads/documents

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# =====================================================
# OLLAMA EMBEDDINGS
# =====================================================

spring.ai.model.embedding=ollama

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.embedding.model=mxbai-embed-large


# =====================================================
# GMAIL SMTP - FORGOT PASSWORD OTP
# =====================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true